//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.LocalServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockInfo", Namespace="http://schemas.datacontract.org/2004/07/Service1")]
    [System.SerializableAttribute()]
    public partial class StockInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClosePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HighestPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LowestPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OpenPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RefPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClosePrice {
            get {
                return this.ClosePriceField;
            }
            set {
                if ((this.ClosePriceField.Equals(value) != true)) {
                    this.ClosePriceField = value;
                    this.RaisePropertyChanged("ClosePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal HighestPrice {
            get {
                return this.HighestPriceField;
            }
            set {
                if ((this.HighestPriceField.Equals(value) != true)) {
                    this.HighestPriceField = value;
                    this.RaisePropertyChanged("HighestPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LowestPrice {
            get {
                return this.LowestPriceField;
            }
            set {
                if ((this.LowestPriceField.Equals(value) != true)) {
                    this.LowestPriceField = value;
                    this.RaisePropertyChanged("LowestPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OpenPrice {
            get {
                return this.OpenPriceField;
            }
            set {
                if ((this.OpenPriceField.Equals(value) != true)) {
                    this.OpenPriceField = value;
                    this.RaisePropertyChanged("OpenPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordIdField, value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RefPrice {
            get {
                return this.RefPriceField;
            }
            set {
                if ((this.RefPriceField.Equals(value) != true)) {
                    this.RefPriceField = value;
                    this.RaisePropertyChanged("RefPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockId {
            get {
                return this.StockIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StockIdField, value) != true)) {
                    this.StockIdField = value;
                    this.RaisePropertyChanged("StockId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockName {
            get {
                return this.StockNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StockNameField, value) != true)) {
                    this.StockNameField = value;
                    this.RaisePropertyChanged("StockName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalServer.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SearchByStockIdJson", ReplyAction="http://tempuri.org/IService/SearchByStockIdJsonResponse")]
        WindowsFormsApp1.LocalServer.StockInfo[] SearchByStockIdJson(string stockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SearchByStockIdJson", ReplyAction="http://tempuri.org/IService/SearchByStockIdJsonResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.LocalServer.StockInfo[]> SearchByStockIdJsonAsync(string stockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SearchByDateJson", ReplyAction="http://tempuri.org/IService/SearchByDateJsonResponse")]
        WindowsFormsApp1.LocalServer.StockInfo[] SearchByDateJson(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SearchByDateJson", ReplyAction="http://tempuri.org/IService/SearchByDateJsonResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.LocalServer.StockInfo[]> SearchByDateJsonAsync(string date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WindowsFormsApp1.LocalServer.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.LocalServer.IService>, WindowsFormsApp1.LocalServer.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.LocalServer.StockInfo[] SearchByStockIdJson(string stockId) {
            return base.Channel.SearchByStockIdJson(stockId);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.LocalServer.StockInfo[]> SearchByStockIdJsonAsync(string stockId) {
            return base.Channel.SearchByStockIdJsonAsync(stockId);
        }
        
        public WindowsFormsApp1.LocalServer.StockInfo[] SearchByDateJson(string date) {
            return base.Channel.SearchByDateJson(date);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.LocalServer.StockInfo[]> SearchByDateJsonAsync(string date) {
            return base.Channel.SearchByDateJsonAsync(date);
        }
    }
}
